app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/themes.xml
- Floating Action Button 컬러 설정 변경
- Bottom Navigation 탭 선택시 컬러 수정
(원래 기본컬러인 보라색으로 나왔는데 배경 색상 없앰)
- Bottom Navigation 수정 사항은 모두에게 반영되어야 할 사항입니다
develop 브랜치 업데이트 해서 확인해주세요
Related to : #6
=> 💄 Feat/home page basicfeat#6

app/src/main/res/layout/fragment_home_upload.xml
게시글 설명 textColor 추가 Related to : #4
게시글 설명에 textColor 설정
Related to : #4
=> :lipstick: Update fragment_home_upload.xml textColor 수정

app/src/main/res/layout/fragment_home_upload.xml
게시글 높이, 마진 수정 Related to : #4
게시글 높이, 마진 수정
Related to : #4
=> :lipstick: Update fragment_home_upload.xml 높이, 마진 수정

app/src/main/java/com/umc/anddeul/home/ConfirmDialog.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/res/drawable/dialog_back_selector.xml, app/src/main/res/layout/dialog_confirm.xml, app/src/main/res/layout/fragment_home.xml
수락 요청 멤버 수락버튼 클릭 시 띄울 커스텀 다이얼로그 생성 & 연결
Related to : #17
=> Feat/home page menu#17

app/src/main/java/com/umc/anddeul/home/PostUploadActivity.kt
갤러리어댑터에 context 넘겨주도록 수정 Related to : #25
- GalleryAdapter를 사용할 때 context 전달
Related to : #25
=> :sparkles: Update PostUploadActivity

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/anddeul/start/StartActivity.kt, app/src/main/java/com/umc/anddeul/start/signin/LoginActivity.kt, app/src/main/java/com/umc/anddeul/start/signin/SignupActivity.kt, app/src/main/java/com/umc/anddeul/start/signin/model/SigninResponse.kt, app/src/main/java/com/umc/anddeul/start/signin/network/SigninInterface.kt, app/src/main/java/com/umc/anddeul/start/signin/service/SigninService.kt, app/src/main/java/com/umc/anddeul/start/terms/TermsActivity.kt
- 파일 위치 변경
- 로그인/회원가입 api 수정
Related to : #10 10
=> ✨Feat/kakao signup login#10

app/src/main/java/com/umc/anddeul/home/PostUploadActivity.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/java/com/umc/anddeul/home/SelectedVPAdapter.kt, app/src/main/res/layout/activity_post_write.xml, app/src/main/res/layout/activity_post_write_selected.xml
- 게시글 업로드 시 선택한 사진들을 슬라이드해서 확인할 수 있도록
ViewPager2를 사용해서 구현 수정
Related to : #25
=> Feat/home page write layout#25

app/build.gradle.kts, app/src/main/java/com/umc/anddeul/home/PostVPAdapter.kt, app/src/main/res/layout/fragment_home_upload.xml, app/src/main/res/layout/fragment_home_upload_image.xml
- 게시글 조회 시 이미지 슬라이드를 위한 ViewPager2 추가 구현
Related to : #4
=> Feat/home page upload layout#4

app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/PostVPAdapter.kt, app/src/main/res/layout/fragment_home_upload.xml
Related to : #4
- 게시글 레이아웃에 사진을 여러장 올렸을 경우 슬라이드로 이미지를 넘기기 위해
ViewPager2 기능 구현 추가
Related to : #4
=> :sparkles: Add 게시글 레이아웃 ViewPager2 추가

app/build.gradle.kts, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/LoadProfileImage.kt, app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/java/com/umc/anddeul/home/model/BoardDTO.kt, app/src/main/java/com/umc/anddeul/home/model/MemberDTO.kt, app/src/main/java/com/umc/anddeul/home/model/PostDTO.kt, app/src/main/java/com/umc/anddeul/home/network/BoardInterface.kt, app/src/main/java/com/umc/anddeul/home/network/MemberInterface.kt
- 게시글 업로드 API 연결
- 홈 메뉴 가족 구성원 조회 API 연결
Related to : #31
=> Feat/home page api#31

app/src/main/res/layout/fragment_postbox.xml
상단바 가로 길이 꽉 차게 수정 Related to : #2
- 상단바 가로 길이 수정
Related to : #2
=> 💄Feat/postbox UI#2-3

app/src/main/AndroidManifest.xml
카카오계정으로도 로그인/회원가입 가능하게 수정 Related to : #10
- 카카오계정 로그인/회원가입 안되는 부분 수정
Related to : #10
=> :sparkles: Update 카카오계정 로그인/회원가입

app/src/main/java/com/umc/anddeul/invite/CreateGroupActivity.kt, app/src/main/java/com/umc/anddeul/invite/CreateGroupCodeActivity.kt, app/src/main/java/com/umc/anddeul/invite/Family.kt, app/src/main/java/com/umc/anddeul/invite/FamilyProfileAdapter.kt, app/src/main/java/com/umc/anddeul/invite/JoinGroupActivity.kt, app/src/main/java/com/umc/anddeul/invite/JoinGroupCodeActivity.kt, app/src/main/java/com/umc/anddeul/invite/model/InviteDTO.kt, app/src/main/java/com/umc/anddeul/invite/network/InviteInterface.kt, app/src/main/java/com/umc/anddeul/invite/service/FamilyAddService.kt, app/src/main/java/com/umc/anddeul/invite/service/FamilyInfoService.kt, app/src/main/java/com/umc/anddeul/invite/service/FamilyNewService.kt, app/src/main/res/layout/activity_create_group_code.xml, app/src/main/res/layout/activity_join_group_code.xml
- 가족 생성 api
- 참여 요청 api
- 참여 요청 정보 api
Related to : #41
=> ✨Feat/invite api#41

app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt
Related to : #31
- 토큰 수정
Related to : #31
=> :memo: Update token 수정

app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileRVAdapter.kt, app/src/main/res/layout/fragment_user_profile.xml, app/src/main/res/layout/fragment_user_profile_post_image.xml
Related to : #43
- 유저 프로필 조회 UI 구현
Related to : #43
=> :lipstick: Add 유저 프로필 UI 구현

app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt, app/src/main/res/layout/fragment_pot.xml
=> 💄Feat/potPageLayout#12

app/src/main/res/layout/fragment_mypage.xml
Related to : #57
- 마이페이지 버튼 크기 LinearLayout으로 수정
=> :lipstick: Update 마이페이지 버튼 크기 수정

app/src/main/res/layout/activity_post_upload.xml, app/src/main/res/layout/activity_post_write.xml
Related to : #25
- 커스텀 갤러리 툴바 크기 조정
Related to : #25
=> :lipstick: Update 게시글 올리기 UI 수정

app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/model/UserProfileDTO.kt
Related to : #58
- 유저 프로필 조회 구조 수정
- 게시글 유저 아이디 전달 오류 수정
- 홈 메뉴 가족 구성원에서 멤버 이름, 프로필 사진 클릭 시 유저 프로필로 이동하도록 추가
Related to : #58
=> :sparkles: Update 유저 프로필 조회 구조 수정, 메뉴 구성원 클릭 시 유저 프로필 이동

app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/model/UserProfileDTO.kt, app/src/main/res/layout/fragment_user_profile.xml
- 유저 프로필 조회 시 firstPostImages 수정
Related to : #58
=> Feat/home user profile api#58

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/anddeul/home/DeleteDialog.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostModifyActivity.kt, app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/UserPostFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/model/OnePostDTO.kt, app/src/main/java/com/umc/anddeul/home/model/PostDeleteDTO.kt, app/src/main/java/com/umc/anddeul/home/model/PostModifyDTO.kt, app/src/main/java/com/umc/anddeul/home/model/UserProfileDTO.kt, app/src/main/java/com/umc/anddeul/home/network/OnePostInterface.kt, app/src/main/java/com/umc/anddeul/home/network/PostDeleteInterface.kt, app/src/main/java/com/umc/anddeul/home/network/PostModifyInterface.kt, app/src/main/res/layout/activity_post_modify.xml, app/src/main/res/layout/fragment_user_post.xml
- 게시글 삭제 api 연결
- 게시글 수정 api 연결
- 유저 프로필에서 각 게시글 조회 api 연결
Related to : #76
=> Feat/home modify delete api#76

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/network/ChecklistInterface.kt
체크리스트 관련 api 수정 Related to #39
체크리스트 api 조회 부분 코드 수정 
=> :sparkles: Fix 체크리스트 API 수정

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/model/AddChecklist.kt, app/src/main/java/com/umc/anddeul/checklist/model/AddChecklistDTO.kt, app/src/main/java/com/umc/anddeul/checklist/model/ChecklistDTO.kt, app/src/main/java/com/umc/anddeul/checklist/network/ChecklistInterface.kt, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt
Fix 체크리스트 api 수정 Related to #39
체크리스트 관련 API DTO 변수명 변경
=> ♻️Feat/checklist api#39 [체크리스트 조회 api 수정]

app/src/main/java/com/umc/anddeul/home/ConfirmDialog.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/model/MemberApproveDTO.kt, app/src/main/java/com/umc/anddeul/home/network/MemberApproveInterface.kt, app/src/main/res/layout/fragment_my_post.xml, app/src/main/res/layout/fragment_mypage_leave.xml, app/src/main/res/layout/fragment_user_post.xml, app/src/main/res/layout/fragment_user_profile.xml, app/src/main/res/layout/toast_anddeul.xml
- 홈 메뉴 가족 승인 api 연결
- 홈 메뉴 가족 코드 복사하기
Related to : #96
=> Feat/home member approve#96

app/src/main/java/com/umc/anddeul/common/AnddeulToast.kt, app/src/main/java/com/umc/anddeul/home/GalleryAdapter.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt
- 커스텀 토스트 AnddeulToast 생성
- 기존 토스트들을 커스텀 토스트로 교체
Related to : #98
=> Feat/custom toast#98

app/src/main/java/com/umc/anddeul/postbox/LetterAdapter.kt, app/src/main/java/com/umc/anddeul/postbox/LetterListFragment.kt, app/src/main/java/com/umc/anddeul/postbox/LetterPopupFragment.kt, app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt, app/src/main/java/com/umc/anddeul/postbox/network/VoiceInterface.kt, app/src/main/java/com/umc/anddeul/postbox/service/VoiceService.kt, app/src/main/res/layout/fragment_letterlist.xml, app/src/main/res/layout/fragment_postbox.xml
- 가족 우체통 api 연결
Related to : #86
=> Feat/postbox api#86

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/AddChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/Checklist.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/DateSet.kt, app/src/main/java/com/umc/anddeul/checklist/model/CheckImgDTO.kt, app/src/main/java/com/umc/anddeul/checklist/model/CompleteDTO.kt, app/src/main/java/com/umc/anddeul/checklist/network/ChecklistInterface.kt, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt, app/src/main/res/layout/activity_add_checklist.xml, app/src/main/res/layout/fragment_checklist.xml, app/src/main/res/xml/file_paths.xml
체크리스트 조회, 추가, 완료 여부 바꾸기 api 수정 및 이미지 첨부 api 연결 수정 Related to #39
체크리스트 관련 API 연결
=> :recycle: Fix 체크리스트 api 연결 및 카메라 연결

app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/mypage/LogoutDialog.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageModifyFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageViewModel.kt, app/src/main/java/com/umc/anddeul/start/StartActivity.kt
- 프로필 수정 에러 viewModel 코드 수정으로 해결
- 로그아웃 후 백버튼 클릭 시 뒤로가기 막기 위해 backPressed 사용
Related to : #106
=> Refac/mypage profile error#106

app/src/main/java/com/umc/anddeul/common/AnddeulToast.kt, app/src/main/res/drawable/toast_background.xml, app/src/main/res/drawable/toast_logo.xml, app/src/main/res/layout/toast_anddeul.xml
Related to : #98
- 커스텀 토스트 UI 수정
- 토스트바 위치 수정
Related to : #98
=> :lipstick: Update 커스텀 토스트 UI 수정

app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt
Related to : #114
- 홈 메뉴에서 가족 구성원의 체크 버튼 클릭 시 체크리스트 화면으로 이동
- 각 유저 프로필에서 체크 버튼 클릭 시 체크리스트로 이동
Related to : #114
=> :sparkles: Add 홈 메뉴 가족 구성원, 유저프로필에서 체크 버튼 클릭 시 체크리스트 화면으로 이동

app/build.gradle.kts, app/src/main/java/com/umc/anddeul/pot/LoadImage.kt, app/src/main/java/com/umc/anddeul/pot/PotFragment.kt, app/src/main/java/com/umc/anddeul/pot/model/FlowerDTO.kt, app/src/main/res/layout/fragment_pot.xml
화분키우기 이미지 관련 api 수정 Related to #91
화분키우기 이미지 관련 api 수정
=> :recycle: Feat/potAPI#91 [이미지 관련 api 수정]

app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/LoadCheckImg.kt, app/src/main/java/com/umc/anddeul/checklist/network/ChecklistInterface.kt, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt, app/src/main/res/layout/activity_add_checklist.xml, app/src/main/res/xml/file_paths.xml
체크리스트 이미지 추가 api 수정 및 이미지 로드 클래스 추가 Related to #39
체크리스트 이미지 추가 api 연결 수정
=> :recycle: Feat/ChecklistAPI#39 [Fix 체크리스트 이미지 추가 api 수정]

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/AddChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/LoadCheckImg.kt, app/src/main/java/com/umc/anddeul/checklist/model/ChecklistDTO.kt, app/src/main/java/com/umc/anddeul/checklist/model/TargetImg.kt, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt, app/src/main/res/layout/fragment_pot.xml, app/src/main/res/layout/item_add_checklist.xml, app/src/main/res/layout/item_checklist.xml
체크리스트 조회 api 이미지 연결 문제 해결 Related to #39
체크리스트 조회 이미지 api 해결 
=> :recycle: Feat/ChecklistAPI#39 [Fix 체크리스트 API 수정]

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/anddeul/home/ConfirmDialog.kt, app/src/main/java/com/umc/anddeul/home/DeleteDialog.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostModifyActivity.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt, app/src/main/java/com/umc/anddeul/mypage/LogoutDialog.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageLeaveFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageModifyFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPostFragment.kt, app/src/main/res/layout/activity_post_write.xml, app/src/main/res/layout/activity_post_write_selected.xml
- 마이페이지 단일조회 시 수정, 삭제 api 연결
- 게시글 작성, 수정 시 키보드에 버튼이 따라올라오는 문제 해결
Related to : #122
=> Feat/mypage modify delete api#122

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/postbox/LetterListFragment.kt, app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt, app/src/main/java/com/umc/anddeul/pot/GardenFragment.kt, app/src/main/java/com/umc/anddeul/pot/LoadImage.kt, app/src/main/java/com/umc/anddeul/pot/PotFragment.kt, app/src/main/java/com/umc/anddeul/pot/model/FlowerDTO.kt, app/src/main/java/com/umc/anddeul/pot/network/PotInterface.kt, app/src/main/res/layout/fragment_garden.xml
화분키우기 api 수정 및 정원 api 수정 Related to #91
화분키우기 및 정원 api 연결, api 수정 
=> :recycle: Feat/potAPI#91 [Fix 화분키우기 api 연결 수정]

app/src/main/java/com/umc/anddeul/postbox/DialogPostSendFragment.kt, app/src/main/java/com/umc/anddeul/postbox/LetterListFragment.kt, app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt, app/src/main/java/com/umc/anddeul/start/StartActivity.kt, app/src/main/java/com/umc/anddeul/start/signin/LoginActivity.kt, app/src/main/java/com/umc/anddeul/start/signin/SignupActivity.kt, app/src/main/res/layout/fragment_dialog_post_send.xml, app/src/main/res/layout/fragment_letterlist.xml, app/src/main/res/layout/fragment_popup_record.xml
날짜별 편지리스트 받은 편지 없을 때
편지 보낸 후 다이얼로그
음성 편지 보낸 후 텍스트 입력 보이게
타이머 가운데
메인 액티비티 뒤로 가기 막기
Related to : #132
=> Feat/postbox detail feat#132

app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/UserPostFragment.kt, app/src/main/java/com/umc/anddeul/home/model/EmojiDTO.kt, app/src/main/java/com/umc/anddeul/mypage/MyPostFragment.kt, app/src/main/res/layout/fragment_home_my_upload.xml, app/src/main/res/layout/fragment_home_upload.xml, app/src/main/res/layout/fragment_my_post.xml, app/src/main/res/layout/fragment_user_post.xml
Related to : #134
- 이모지 3개 모두 선택 가능하도록 수정
Related to : #134
=> :sparkles: Update 이모지 3개 모두 선택 가능하도록 수정

app/src/main/res/layout/activity_post_upload.xml, app/src/main/res/layout/activity_post_write.xml, app/src/main/res/layout/fragment_home_my_upload.xml, app/src/main/res/layout/fragment_home_upload.xml, app/src/main/res/layout/fragment_my_post.xml, app/src/main/res/layout/fragment_mypage_leave.xml, app/src/main/res/layout/fragment_mypage_modify_profile.xml, app/src/main/res/layout/fragment_mypage_notification.xml, app/src/main/res/layout/fragment_mypage_setting.xml, app/src/main/res/layout/fragment_user_post.xml, app/src/main/res/layout/fragment_user_profile.xml, app/src/main/res/layout/fragment_user_profile_post_image.xml
- 툴바 하단 view 추가
- 게시글 뷰페이저 크기 조정
- 유저 프로필 조회 시 게시글 이미지 크기 조정
Related to : #138
=> Style/toolbar view#138

app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/UserPostFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPostFragment.kt
Related to : #134
- 이모지 취소 시 이모지 레이아웃 숨기기
Related to : #134
=> :sparkles: Add 이모지 취소 시 레이아웃 숨기기

app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageModifyFragment.kt
Related to : #146
- 게시글 작성 시 이미지 압축 후 서버에 전송
- 프로필 사진 수정 시 이미지 압축 후 서버에 전송 
Related to : #146
=> :recycle: Refac 게시글 작성, 프로필 수정 시 이미지 크기 압축

app/src/main/res/drawable/ic_anddeul_background.xml, app/src/main/res/mipmap-anydpi-v26/ic_anddeul.xml, app/src/main/res/mipmap-anydpi-v26/ic_anddeul_round.xml, app/src/main/res/values/ic_anddeul_background.xml
=> :lipstick: Update 앱 아이콘 크기 조정

app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt
Related to : #114
- 체크리스트로 이동 시 해당 멤버 이름 전달 추가
Related to : #114
=> :recycle: Update 체크리스트로 이동 시 해당 멤버 이름 전달 추가

app/src/main/java/com/umc/anddeul/postbox/LetterListFragment.kt, app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt, app/src/main/java/com/umc/anddeul/postbox/RecordPopupFragment.kt, app/src/main/java/com/umc/anddeul/start/signin/LoginActivity.kt, app/src/main/java/com/umc/anddeul/start/signin/SignupActivity.kt
Rlelated to : #151
Related to : #151
=> :fire: Delete 불필요 코드

app/src/main/res/layout/activity_create_group.xml, app/src/main/res/layout/activity_create_group_code.xml, app/src/main/res/layout/activity_join_group.xml, app/src/main/res/layout/activity_join_group_code.xml, app/src/main/res/layout/activity_join_group_send.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_signup.xml, app/src/main/res/layout/activity_terms.xml, app/src/main/res/layout/fragment_letterlist.xml, app/src/main/res/layout/fragment_postbox.xml
=> :lipstick: Add 배경색

app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt
체크리스트 완료 함수 수정 Related to #39
완료 api 수정
=> ♻️ Feat/checklist api#39 [완료 api 수정]

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt
체크리스트 추가 함수 주석 처리 수정 Related to #39
=> :recycle: Fix 체크리스트 추가 함수 주석 처리

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt
=> :recycle: 추가 함수 수정

app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt
=> :Fix 체크리스트 달력 UI

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt
=> :lipstick: 체크리스트 add 달력 ui 수정

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/LoadCheckImg.kt, app/src/main/java/com/umc/anddeul/pot/GardenFragment.kt, app/src/main/java/com/umc/anddeul/pot/PotFragment.kt
코드 주석 및 로그 정리 Related to #166
주석 삭제 및 오류 문장 삭제
=> :recycle: Feat/CodeClearly#166 [Fix 코드 주석 및 로그 정리]

app/src/main/AndroidManifest.xml
작업하기 편하게 앱 실행 시 로그인 과정 생략 함. 
추후 다시 앱 실행 시 로그인 하도록 변경해야 함
Related to : #172
Related to : #172
=> :sparkles: Update 앱 실행 시 로그인 과정 생략

app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/common/RetrofitManager.kt, app/src/main/java/com/umc/anddeul/home/ConfirmDialog.kt, app/src/main/java/com/umc/anddeul/home/DeleteDialog.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostModifyActivity.kt, app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/java/com/umc/anddeul/home/UserPostFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileRVAdapter.kt, app/src/main/java/com/umc/anddeul/mypage/LogoutDialog.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageLeaveFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageModifyFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPostFragment.kt
Related to : #177
- RetrofitManager 파일 생성
- retrofitBearer 관련 코드들 수정
Related to : #177
=> :recycle: Update retrofitBearer 코드 수정

.idea/gradle.xml, app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/home/EmojiRVAdpater.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/PostVPAdapter.kt, app/src/main/java/com/umc/anddeul/home/UserPostFragment.kt, app/src/main/java/com/umc/anddeul/home/model/EmojiDTO.kt, app/src/main/java/com/umc/anddeul/home/model/OnePostDTO.kt, app/src/main/java/com/umc/anddeul/home/model/PostDTO.kt, app/src/main/java/com/umc/anddeul/mypage/MyPostFragment.kt, app/src/main/res/drawable/emoji_back_non_select.xml, app/src/main/res/layout/fragment_home_my_upload.xml, app/src/main/res/layout/fragment_home_upload.xml, app/src/main/res/layout/fragment_my_post.xml, app/src/main/res/layout/fragment_user_post.xml, app/src/main/res/layout/item_emoji_non_selected.xml, app/src/main/res/layout/item_emoji_selected.xml
- 전체 게시글 조회 이모지 api 연결
- 단일 게시글 조회 이모지 api 연결
Issue Number:  #174
=> Feat/emoji api modify#174

app/src/main/res/layout/activity_create_group.xml, app/src/main/res/layout/activity_create_group_code.xml, app/src/main/res/layout/activity_invite_start.xml, app/src/main/res/layout/activity_join_group.xml, app/src/main/res/layout/activity_join_group_code.xml, app/src/main/res/layout/activity_join_group_send.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_signup.xml, app/src/main/res/layout/activity_start.xml, app/src/main/res/layout/activity_terms.xml
=> Style/signin modify UI#187

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/model/ChecklistDTO.kt
체크리스트 카메라 관련 기능 수정
체크리스트 사진 api 1차 수정
=> :recycle:Feat/ChecklistAPI#39

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/home/DragAndDropHelper.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostModifyActivity.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/java/com/umc/anddeul/home/SelectedVPAdapter.kt, app/src/main/java/com/umc/anddeul/home/network/OnePostInterface.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageFragment.kt, app/src/main/res/layout/fragment_user_profile_post_image.xml
- 커스텀 갤러리 삭제
- 포토 피커 구현
- 포토 피커 사용 안할 경우 권한 확인 (API 버전 30 미만)
- API 버전 30 미만 - 기본 갤러리 연결
- 게시글 작성 시 드래그 앤 드랍으로 사진 순서 변경
- 드래그 앤 드랍을 구현해봤는데 뭔가 부자연스러운 느낌이 있는 것 같아요 😂
- API 30 미만은 권한 확인하고 기본 갤러리를 열어서 사진 선택하도록 구현해뒀습니다
(포토피커 지원하는 버전은 권한 확인 x)
- 토큰 유효기간이 끝나서 토큰 수정, UI 수정 파일이 같이 들어가 있는데 이건 신경 안쓰셔도 됩니다!
Issue Number:  #185
=> Feat/modify gallery#185

app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/model/MemberDTO.kt
Related to : #201
- MemberDTO에 family_name 추가
- Home에서 drawerLayout을 통해 가족구성원 조회 시 그룹 이름 반영
Issue Number:  #201
=> :sparkles: Update 가족 구성원 조회 시 그룹 이름 반영

app/src/main/res/drawable/toast_error_background.xml, app/src/main/res/layout/toast_error_anddeul.xml
=> 💄 Feat/toast bar UI#204

.idea/gradle.xml, .idea/misc.xml, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/common/AnddeulErrorToast.kt, app/src/main/res/layout/toast_error_anddeul.xml
서버 에러 토스트 객체 추가 및 토스트 위치 조정 Related to #204
=> :sparkles: Feat/ToastBarUI#204

app/src/main/java/com/umc/anddeul/home/DragAndDropHelper.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/res/layout/activity_post_write.xml, app/src/main/res/values/dimens.xml
=> :sparkles: Update 드래그 앤 드롭 시 이미지 크기 변경 - 수정

.idea/gradle.xml, app/src/main/java/com/umc/anddeul/home/DragAndDropHelper.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/res/values/dimens.xml
- 드래그 앤 드롭으로 이미지 순서 변경
- 드래그 앤 드롭 시 아이템 크기 변경
Issue Number:  #203
=> Feat/drag and drop#203

app/src/main/java/com/umc/anddeul/MainActivity.kt
임시로 우체통 하단바 알림 주석 처리
Related to : #209
=> Feat/postbox bottom alarm#209

app/src/main/res/layout/fragment_letterlist.xml, app/src/main/res/layout/fragment_postbox.xml
주간 달력 숫자 안잘리게 UI 수정
Related to : #180
=>  Feat/PostboxNewUI#180

app/src/main/java/com/umc/anddeul/postbox/LetterListFragment.kt, app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt, app/src/main/java/com/umc/anddeul/postbox/service/FamilyService.kt, app/src/main/java/com/umc/anddeul/postbox/service/MailService.kt, app/src/main/java/com/umc/anddeul/postbox/service/PostboxAlarmService.kt, app/src/main/java/com/umc/anddeul/postbox/service/QuestionService.kt, app/src/main/java/com/umc/anddeul/postbox/service/ReadMailService.kt, app/src/main/java/com/umc/anddeul/postbox/service/TextService.kt, app/src/main/java/com/umc/anddeul/postbox/service/VoiceService.kt
=> Feat/postbox api log#217

.idea/misc.xml, app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/model/ChecklistDTO.kt, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt, app/src/main/java/com/umc/anddeul/pot/GardenFragment.kt, app/src/main/java/com/umc/anddeul/pot/PotFragment.kt
체크리스트 api 로그 수정 및 코드 정리 Related to #39
=> :recycle: Feat/ChecklistAPI#39

app/src/main/res/layout/activity_add_checklist.xml, app/src/main/res/layout/fragment_checklist.xml
=> 💄Feat/ChecklistAPI#39

app/src/main/java/com/umc/anddeul/invite/CreateGroupActivity.kt, app/src/main/java/com/umc/anddeul/invite/JoinGroupActivity.kt, app/src/main/java/com/umc/anddeul/invite/JoinGroupCodeActivity.kt, app/src/main/java/com/umc/anddeul/start/signin/LoginActivity.kt, app/src/main/java/com/umc/anddeul/start/signin/SignupActivity.kt
=> :sparkles: Add 서버 에러 토스트

app/src/main/java/com/umc/anddeul/MainActivity.kt
가족우체통 하단바 알림 방법 바꿈
Related to : #209
#209
=> :sparkles: Update 가족우체통 하단바 알림

.idea/gradle.xml, app/src/main/java/com/umc/anddeul/common/AnddeulErrorToast.kt, app/src/main/java/com/umc/anddeul/common/AnddeulToast.kt, app/src/main/java/com/umc/anddeul/home/DeleteDialog.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/PostModifyActivity.kt, app/src/main/java/com/umc/anddeul/home/PostRVAdapter.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/java/com/umc/anddeul/home/UserPostFragment.kt, app/src/main/java/com/umc/anddeul/home/UserProfileFragment.kt, app/src/main/java/com/umc/anddeul/mypage/LogoutDialog.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageLeaveFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageModifyFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPostFragment.kt
Related to : #214
- 서버 에러 메시지 처리
- onResponse지만 실패한 경우 : PM님이 정리해주신 메세지 (에러 토스트바)
- onFailure인 경우 : "서버 연결이 불안정합니다"로 통일 (에러 토스트바)
Issue Number:  #214
=> :sparkles: Add 서버 에러 메세지 처리

app/src/main/java/com/umc/anddeul/ext/RvExt.kt, app/src/main/java/com/umc/anddeul/home/DeleteDialog.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/model/PostDTO.kt, app/src/main/java/com/umc/anddeul/home/network/PostsInterface.kt
- 홈 피드 불러오기 페이징 처리
Issue Number:  #227
=> Refac/home paging#227

app/src/main/java/com/umc/anddeul/common/AnddeulErrorToast.kt, app/src/main/java/com/umc/anddeul/common/AnddeulNoLogoToast.kt, app/src/main/java/com/umc/anddeul/common/AnddeulToast.kt, app/src/main/java/com/umc/anddeul/ext/IntExt.kt, app/src/main/java/com/umc/anddeul/home/PostWriteActivity.kt, app/src/main/res/layout/toast_no_logo.xml
- 게시글 작성 시 드래그 앤 드랍으로 사진 순서를 이동시킬 수 있는 안내 토스트바 추가
- 토스트바에서 Int를 Px로 바꿔주는 함수 확장함수로 변환
- 게시글 작성 프래그먼트 코드 구조 수정
Issue Number:  #229
=> Style/drag and drop toast#229

app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/model/AddChecklistDTO.kt, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt
체크리스트 api 관련 오류 수정
체크리스트 토스트바 추가 및 수정
=> ♻️Feat/ChecklistAPI#39

app/src/main/java/com/umc/anddeul/ext/ContextExt.kt, app/src/main/java/com/umc/anddeul/home/ConfirmDialog.kt, app/src/main/java/com/umc/anddeul/home/DeleteDialog.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/mypage/LogoutDialog.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageModifyFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPostFragment.kt, app/src/main/res/layout/fragment_mypage.xml
- 마이페이지 새로고침 추가
- DeleteDialog 로직 수정
Issue Number: #239
=> Refac/mypage refresh#239

app/src/main/java/com/umc/anddeul/start/StartActivity.kt, app/src/main/java/com/umc/anddeul/start/model/TokenResponse.kt, app/src/main/java/com/umc/anddeul/start/network/TokenInterface.kt, app/src/main/java/com/umc/anddeul/start/service/TokenService.kt
- 자동 로그인 토큰 유효 판별 추가
#248 
#248
=> Feat/auto login token#248

app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt, app/src/main/java/com/umc/anddeul/home/HomeFragment.kt, app/src/main/java/com/umc/anddeul/home/SaveDataHandler.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageFragment.kt, app/src/main/java/com/umc/anddeul/mypage/MyPageLeaveFragment.kt, app/src/main/java/com/umc/anddeul/mypage/model/SelectLeaderDTO.kt, app/src/main/java/com/umc/anddeul/mypage/network/LeaveInterface.kt, app/src/main/java/com/umc/anddeul/mypage/network/SelectLeaderInterface.kt, app/src/main/res/layout/fragment_mypage_leave.xml
- 탈퇴 시 다음 방장 선택하기 api 연결
- spf 저장 함수들 클래스로 만들어 구조 수정
- 본인이 방장일 시에만 다음 방장 선택하도록 Ui 수정
Issue Number:  #242
=> Feat/select leader api#242

.idea/gradle.xml, app/build.gradle.kts, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt, app/src/main/java/com/umc/anddeul/pot/GardenFragment.kt, app/src/main/java/com/umc/anddeul/pot/PotFragment.kt, app/src/main/java/com/umc/anddeul/pot/model/FlowerDTO.kt, app/src/main/java/com/umc/anddeul/pot/network/PotInterface.kt, app/src/main/res/drawable/ic_pot_before.xml, app/src/main/res/layout/fragment_garden.xml, app/src/main/res/layout/fragment_pot.xml
화분 키우기 및 정원 api 수정 Relatedt to #39
=> :recycle: Update화분키우기 api 수정

app/src/main/java/com/umc/anddeul/postbox/LetterListFragment.kt, app/src/main/java/com/umc/anddeul/postbox/LetterPopupFragment.kt, app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt, app/src/main/java/com/umc/anddeul/postbox/service/FamilyService.kt, app/src/main/java/com/umc/anddeul/postbox/service/MailService.kt, app/src/main/java/com/umc/anddeul/postbox/service/QuestionService.kt, app/src/main/java/com/umc/anddeul/postbox/service/ReadMailService.kt, app/src/main/java/com/umc/anddeul/postbox/service/TextService.kt, app/src/main/java/com/umc/anddeul/postbox/service/VoiceService.kt
401 에러 시 로그아웃 처리
Related to : #250
=> :sparkles: Add 가족우체통 401 에러 로그아웃 처리

.idea/gradle.xml, app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt
랜덤 질문 api 위치 아래로 이동
Related to : #274
=> :recycle: Refac: 랜덤 질문 관련 코드 위치 이동

app/src/main/java/com/umc/anddeul/MainActivity.kt
알림 api 실행 함수 추가 related to #277
=> :recycle: Update 알림 api 연결

app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/AddChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/model/AddChecklistDTO.kt, app/src/main/java/com/umc/anddeul/checklist/model/ChecklistDTO.kt, app/src/main/java/com/umc/anddeul/checklist/model/CompleteDTO.kt, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt, app/src/main/res/layout/activity_add_checklist.xml
체크리스트 추가 api 수정 및 DTO 구조 변경 related to #283
=> :recycle: Update 체크리스트 추가 api 수정

app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/checklist/AddChecklistActivity.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistFragment.kt, app/src/main/java/com/umc/anddeul/checklist/ChecklistRVAdapter.kt, app/src/main/java/com/umc/anddeul/checklist/model/ChecklistDTO.kt, app/src/main/java/com/umc/anddeul/checklist/model/CompleteDTO.kt, app/src/main/java/com/umc/anddeul/checklist/service/ChecklistService.kt
이미지 추가 api 및 DTO 구조, 달력 오류 수정 related to #289
=> :recycle: Update 이미지 추가 api 수정

app/src/main/java/com/umc/anddeul/MainActivity.kt, app/src/main/java/com/umc/anddeul/pot/GardenFragment.kt, app/src/main/java/com/umc/anddeul/pot/PotFragment.kt
=> :recycle: Update 정원 api 테마 수정

app/src/main/java/com/umc/anddeul/postbox/PostboxFragment.kt
API 문제 해결되어 API 주석 해제
Related to : #296
=> :sparkles: Update 오늘의 질문 주석 해제

app/src/main/java/com/umc/anddeul/invite/CreateGroupCodeActivity.kt
=> ♻️ 가족 코드 공유 에러 해결 및 수정
